#!/bin/bash
confpath=/etc/nagios3/conf.d/contactgroups

getcnattr()
{
	cn=$1
	attr=$2
	ldapsearch -x "(cn=$cn)" $attr | grep $attr: | cut -d' ' -f 2
}

getuidattr()
{
	uid=$1
	attr=$2
	ldapsearch -x "(uid=$uid)" $attr | grep $attr: | cut -d' ' -f 2
}

# Check ldap
ldapsearch -x '(uid=)' > /dev/null
status=$?
if [ $status -ne 0 ]; then
	echo 'LDAP read failed!'
	exit $status
fi

# Get config files
groups=$(ls $confpath | cut -d. -f1)

# For each config file, get nagios members
echo "$groups" | while read cn; do
	members=$(
		getcnattr $cn memberUid | while read uid; do
			iscontact=$(getuidattr $uid objectClass | grep nagiosContact | wc -l)
			if [ $iscontact -eq 1 ]; then
				echo $uid
			fi
		done | head -c-1 | tr "\n" ','
	)
	
	# And write
	cat > "$confpath/$cn.cfg" << EOF
## Managed by ldap
define contactgroup {
	contactgroup_name	$cn
	alias			$cn
	members			$members
}
EOF
done
